README.md

Please merge after Travis activation and edit url accordingly if needed.

Updated Readme to reflect build status.

---

.gitattributes

Make configs more eye-candy while viewing online.

Add Linguist syntax highlighting support

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

While I almost finished rebuilding my world w/ LTO (I'll wait a few days for  kde-frameworks 5.39) here is information I collected.
Please note: converted from my package.env so I'm not sure about flag-format in package.cflags.

More info + packages

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

https://github.com/InBetweenNames/gentooLTO/issues/78

media-libs/mesa: disable lto only with video_cards_nouveau

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

media-libs/mesa: this version is dropped, 17.3.0 builds fine

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

app-cdr/cdrtools: Disable LTO

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

sci-electronics/kicad no LTO - Issue #168

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

app-doc/doxygen: added to the ninja blacklist.

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

dev-lang/R: disable "${IPA}"

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

dev-libs/libsigsegv: disable LTO

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

media-sound/mpc: building with -fipa-pta causes hang on exit

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Added workaround for sys-apps/fwupd

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Add workaround for sys-apps/nix

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Removed trailing whitespaces from ltoworkarounds

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Revert the accidental reversal of #272 which occurred in 3008105fff17b9bdf2efa34cb741c12c622b5bd9
Reported by @huglovefan

media-libs/flac: re-introduce #272

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

>=sys-apps/attr-2.4.48: disable LTO

---

metadata/news/2019-04-17-results/2019-04-17-results.en.txt

The description says it all :)

Fix my name in news file

---

sys-config/ltoize/files/make.conf.lto.defines

It has been annoying me for MONTHS

Remove trailing whitespace

---

sys-config/ltoize/files/make.conf.lto.defines
sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Added the workarounds I use on my Ofast machines (amd64 KDE plasma). I expect we are missing a bunch from other desktop environments/architectures/etc, but hopefully these can get us started.

Added handful of Ofast workarounds

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

sys-apps/sandbox: disable LTO

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

x11-libs/wxGTK: filter -Wl flags out of C*FLAGS

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

sys-libs/ncurses-compat
Fixes #418

Copied ncurses patch to ncurses-compat

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

sci-libs/scipy: graphite ICE

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

sys-libs/libcap: use ld.bfd

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Title: sys-cluster/glusterfs: adds missing '-'

Add missing '-' on the glusterfs entry

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

dev-lang/ocaml: remove -fipa-pta

---

sys-config/ltoize/ltoize-0.9.6-r1.ebuild

Title: sys-config/ltoize: USE=keep-nocommon dosym for nocommon.conf fix
fixes https://github.com/InBetweenNames/gentooLTO/issues/553

sys-config/ltoize USE=keep-nocommon dosym for nocommon.conf fix

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

games-arcade/supertux: CMAKE_MAKEFILE_GENERATOR=emake

---

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf

Add missing asterisk on LLVM workarounds

---

app-portage/lto-rebuild/lto-rebuild-0.9.8.ebuild

lto-rebuild: fix rdepends, install phase

---

dev-lang/python/python-2.7.18-r100.ebuild
dev-lang/python/python-3.10.0_alpha3-r1.ebuild
dev-lang/python/python-3.5.5-r2.ebuild
dev-lang/python/python-3.6.12-r1.ebuild
dev-lang/python/python-3.7.9-r1.ebuild
dev-lang/python/python-3.8.7-r1.ebuild
dev-lang/python/python-3.9.1-r1.ebuild

Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Theo Anderson <telans@posteo.de>

dev-lang/python: fix test_distutils sandbox violations

---

sys-config/ltoize/files/package.cflags/lto.conf

www-misc/shellinabox: disable LTO

---

sys-config/ltoize/files/package.cflags/lto.conf

net-misc/autossh: disable LTO

---

sys-config/ltoize/files/package.cflags/lto.conf

dev-libs/libbpf: disable LTO

---

sys-config/ltoize/files/package.cflags/lto.conf

dev-util/cargo-c: add -ffat-lto-objects to fix link failure
