README.md
Great work. It would be interesting to add another package.env file to filter out -O3 optimizations from packages which actually perform worse with -O3.
=> Removed duplicate sys-libs/gpm entry

package.env/ltoworkarounds.conf
Vim doesn’t build with LTO with perl support, but builds fine without it.
=> Add app-editors/vim to ltoworkarounds.conf

sys-config/ltoize/files/package.env/ltoworkarounds.conf
The package moarvm (an indirect dependency for Perl6) needs to be ltofat.conf for dev-lang/nqp and dev-lang/rakudo to compile and link.
=> Pkg moarvm made ltofat.conf so nqp and rakudo can build for Perl6.

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Patched for GCC7: https://bugs.gentoo.org/629570
[ 5411.704512] pulseaudio[17609]: segfault at 7f04ceeb8096 ip 00007f04beb3a8af sp 00007ffdf5fecef0 error 4 in libjack.so.0.1.0[7f04beb28000+38000]
[ 5439.833653] calfjackhost[17699]: segfault at 7f0cde2a908e ip 00007f0cdc707a7f sp 00007f0cca282bc0 error 4 in libjack.so.0.1.0[7f0cdc6f9000+38000]
[ 5488.924652] qjackctl[16377]: segfault at 559bdd7ae068 ip 00007f15c61eedfe sp 00007ffcf9c3c260 error 6 in libc-2.26.so[7f15c60d9000+1bf000]
I created separate section for packages w/ similar problems to make the list more informative.
=> media-sound/jack2: LTO not recommended

sys-config/ltoize/files/make.conf.lto
I have all packages built w/ this for now and no noticeable problems so far. The only `-flto` overrides left is (as have some build errors):
```sh
media-libs/alsa-lib
media-libs/flac
```
and this two (unstable w/ LTO):
```sh
net-misc/openssh
media-sound/jack2
```
Some other locally patched to be built w/ LTO or have additional flags.
So for now I have ~1K packages installed and still no any `-ffat-lto-objects` flags set.
=> Support more LTOed packages

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
There is possible to add some logic to `*FLAGS` ( https://github.com/vaeth/portage-bashrc-mv/issues/8#issuecomment-338497760 ) so we can check is USE-flag set etc. You probably may want to add similar logic for `BEGIN: genkernel no LTO needs for initramfs use of LVM + LUKS` block and other packages.
=> Use some overrides only for specified USE-flag

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
*FLAGS+="-flto-partition=max" don't work for dev-lang/php:7.2 anymore
=> dev-lang/php: fix LTO for version >= 7.2

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> media-libs/openal: 1.18.2-r1 needs graphite disabled to build

dev-lang/python/python-3.4.6-r2.ebuild, dev-lang/python/python-3.5.4-r2.ebuild, dev-lang/python/python-3.6.4-r1.ebuild
Title: <category>/<package>: <description>
Ensure that any added workarounds have a comment explaining the compilation error which requires it.
Any removed workarounds should be moved to the fixed section.
If an issue exists, please link it.
See CONTRIBUTING.md for more information.
=> Added exclusions to pass pgo profile tests, overcome permission errors

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
currently `xf86-video-intel` does not build with LTO. disabling it fixes the issue.
**Relevant build error:**
`error: inlining failed in call to always_inline ‘memcpy’: target specific option mismatch`
which apparently, is a [GCC memory starvation issue](https://bugs.freedesktop.org/show_bug.cgi?id=77580)
=> Disable LTO for x11-drivers/xf86-video-intel

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Title: app-misc/vlock: fails with ```gcc: error trying to exec '/usr/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/collect2': execv: Argument list too long``` unless I disable LTO completely.
from the error log it seems like it's more of a build system problem than LTO itself
full log https://gist.github.com/anonymous/cd87a7af30314bbb9d90ec49073294e4
=> app-misc/vlock: disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
the build currently fails with the following error:
```
Error: can't resolve `.rodata' {.rodata section} - `.Ltext0' {.text section}
gcc error: ld-wrapper failed.
```
disabling lto fixes it.
=> app-text/mupdf: disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> =media-libs/openjpeg-2.3.0 doesnt compile with graphite, #98

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Doesn't seem to build with full LTO or with fat objects enabled.
Build log: [dev-scheme:racket-6.12:20180221-014120.txt](https://github.com/InBetweenNames/gentooLTO/files/1742660/dev-scheme.racket-6.12.20180221-014120.txt)
=> dev-scheme/racket: disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
`app-emulation/wine-staging` compiles for me with GCC 8.1.0 and graphite enabled.
=> app-emulation/wine*: can be built with graphite

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Noticed a failure for dev-db/mysql-connector-c when utilizing LTO. Added exception and compilation proceeds normally. Please let me know if there are any issues.
Thanks!
=> dev-db/mysql-connector-c: Added LTO exception to allow compilation

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> net-p2p/retroshare: disable LTO due to ICE on amd64

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Reference build error:
```
/bin/sh /var/tmp/portage/dev-lang/php-7.2.7/work/sapis-build/cli/libtool --silent --preserve-dup-deps --mode=install cp ext/opcache/opcache.la /var/tmp/portage/dev-lang/php-7.2.7/work/sapis-build/cli/modules
/var/tmp/portage/dev-lang/php-7.2.7/work/sapis-build/cli/ext/curl/interface.c: In function '_php_curl_setopt':
/var/tmp/portage/dev-lang/php-7.2.7/work/sapis-build/cli/ext/curl/interface.c:2803:4: warning: call to '_curl_easy_setopt_err_progress_cb' declared with attribute warning: curl_easy_setopt expects a curl_progress_callback argument for this option
curl_easy_setopt(ch->cp, CURLOPT_PROGRESSFUNCTION, curl_progress);
^
/var/tmp/portage/dev-lang/php-7.2.7/work/sapis-build/cli/Zend/zend_vm_execute.h: In function 'ZEND_TICKS_SPEC_HANDLER': …
```
=> dev-lang/php: address #135 (linking for >=php-7.2)

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
[build.txt](https://github.com/InBetweenNames/gentooLTO/files/2485412/build.txt)
[info.txt](https://github.com/InBetweenNames/gentooLTO/files/2485413/info.txt)
```
x86_64-pc-linux-gnu-gcc  -march=native -O3 -fgraphite-identity -floop-nest-optimize -flto=4 -fipa-pta -fuse-linker-plugin -pipe -fomit-frame-pointer -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -DNDEBUG  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -flto=4 -fipa-pta -fuse-linker-plugin -pipe -fomit-frame-pointer -Wl,-export-dynamic -o gawk array.o awkgram.o builtin.o cint_array.o command.o debug.o dfa.o eval.o ext.o field.o floatcomp.o gawkapi.o gawkmisc.o getopt.o getopt1.o int_array.o io.o main.o mpfr.o msg.o node.o profile.o random.o re.o regex.o replace.o …
```
=> sys-apps/gawk: disable -fipa-pta

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
`sys-apps/exa` fails to build with fat LTO, for the same reasons I guess that `cargo` does.
=> sys-apps/exa: fails to link to git2 with fat LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Compiling llvm with semantic flag causes wine with DXVK either freeze or crash. Steam play/Proton is also affected, however native vulkan games on Linux is unaffected like RoTTR.
My gpu: AMD VEGA 64
=> sys-devel/llvm with SEMINTERPOS makes DXVK crash

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Polybar will not build with ninja; added line to use emake. See [issue](https://github.com/InBetweenNames/gentooLTO/issues/175)
=> x11-misc/polybar: use emake instead of ninja

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
See #209 
Basically, it builds fine but we cannot set any ACLs at all.
=> sys-apps/acl fails to set ACLs if built with LTO.

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Signed-off-by: Andrew Attali <me@aphypnise.eu>
Racket needs to be built without LTO and -fipa-pta, since some references are used by the racket compiler during installation. This prevents segfaults and undefined references.
=> dev-scheme/racket: fails to build with LTO and -fipa-pta

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
See #204
Signed-off-by: Andrew Attali <me@aphypnise.eu>
=> dev-java/openjdk: fails to build without LTO off.

sys-config/ltoize/ltoize-0.8.1.ebuild, sys-config/ltoize/ltoize-0.8.2.ebuild, sys-config/ltoize/ltoize-0.9.0.ebuild, sys-config/ltoize/ltoize-0.9.1.ebuild
I am not sure, but GCC version in warning message is not equal to "${ACTIVE_GCC}" -lt 8.2.0
=> Fix GCC version number in warning message

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Compiling SBCL fails during IPA pass.
=> dev-lisp/sbcl: cannot build with -fipa-pta

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
With -fno-semantic-interposition builds fine but crashes with:
> automount[9179]: segfault at 0 ip 00007ff50bd65488 sp 00007fffa36d3070 error 4 in lookup_file.so[7ff50bd4c000+36000]
=> net-fs/autofs: no-semantic-interposition segfaults

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
[build.log with GRAPHITE enabled](https://ptpb.pw/es8N.log)
[build.log without GRAPHITE enabled](https://ptpb.pw/oxmD.log)
=> dev-lang/ocaml: disable GRAPHITE due to ICE

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Building media-libs/openexr with LTO fails with:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `pthread_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_wait'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_init'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined …
```
=> media-libs/ilmbase: -lrt needed to build openexr

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
```
undefined reference to 'git_repository_discover'
undefined reference to 'git_repository_open'
undefined reference to 'ansi256_from_rgb'
undefined reference to 'ansi256_from_rgb'
undefined reference to 'OnigEncodingUTF8'
undefined reference to 'onig_search_with_param'
undefined reference to 'mz_deflate'
undefined reference to 'mz_deflateInit2'
undefined reference to 'mz_inflateInit2'
undefined reference to 'mz_inflate'
undefined reference to 'mz_deflateEnd'
undefined reference to 'mz_inflateEnd'
undefined reference to 'onig_region_free'
undefined reference to 'onig_free_match_param'
undefined reference to 'onig_error_code_to_str'
undefined reference to 'OnigDefaultSyntax'
undefined reference to 'OnigEncodingUTF8'
undefined reference to 'onig_new'
undefined reference to …
```
=> sys-apps/bat: fails to link

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Similar to https://github.com/InBetweenNames/gentooLTO/issues/129, compilation fails with error:
`lto1: internal compiler error: in get_odr_type, at ipa-devirt.c:2098`
Removing LTO allowed it to compile.
=> Added workaround for sci-visualization/paraview

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
**Compilation error:**
```
[ 83%] Linking CXX executable qtox
/usr/bin/cmake -E cmake_link_script CMakeFiles/qtox.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-g++  -march=skylake -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -flto=7 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Werror -fstack-protector-all -Wstack-protector  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=skylake -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -flto=7 -fuse-linker-plugin -pipe -Wl,-z,now -Wl,-z,relro -rdynamic CMakeFiles/qtox.dir/qrc_res.cpp.o …
```
=> net-im/qtox: Disable LTO to solve compilation error

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
media-libs/libwebp: -fipa-pta causes browsers (tested with firefox and chrome) to incorrectly display webp images.
=> Added -fipa-pta workaround for libwebp.

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Shotwell does not build with LTO enabled.
=> media-gfx/shotwell: Disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=app-emulation/libguestfs-1.38.6 compilation fails with the following error:
`libtool: link: x86_64-pc-linux-gnu-gcc -o /var/tmp/portage/app-emulation/libguestfs-1.38.6/work/libguestfs-1.38.6/gobject/tmp-introspectwljek7i2/.libs/Guestfs-1.0 -march=native -O3 -fgraphite-identity -floop-nes
t-optimize -fipa-pta -fno-semantic-interposition -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 -Wl,-O1 -Wl,--hash-style=gnu -fno-strict-overflow -Wno-strict-overflow /var/tmp/portage/app-emulation/libgu
estfs-1.38.6/work/libguestfs-1.38.6/gobject/tmp-introspectwljek7i2/Guestfs-1.0.o -Wl,--export-dynamic -pthread -Wl,-O1 -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fipa-pta -f
no-semantic-interposition -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 …
=> Added workaround for app-emulation/libguestfs

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
the latest version of bspwm wouldn't compile on my system without this workaround
=> x11-wm/bspwm: IPA workaround

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> dev-libs/isl: work around execv argument list too long upon linking

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> dev-tex/chktex: disable LTO when pcre in USE, to work around link failure

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> media-libs/flac: disables -O3 default -fipa-cp-clone as it breaks flac -d with LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
this fixes off-sounding aac playback in deadbeef (from deadbeef-overlay) when faad2 is compiled with -O3
=> add workaround for media-libs/faad2

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Reverts InBetweenNames/gentooLTO#265
As indicated in InBetweenNames/gentooLTO#264, the workaround is no longer necessary with GCC-8.3.0-r1.
=> Revert "dev-libs/isl: work around execv argument list too long upon linking"

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
app-misc/tracker makes gnome-base/nautilus deadlock on start if it is compiled with ${SEMINTERPOS}.
Take a look at https://forums.gentoo.org/viewtopic-p-8324442.html and https://github.com/InBetweenNames/gentooLTO/issues/275 for more details.
=> app-misc/tracker: remove seminterpos

app-portage/lto-rebuild/files/lto-rebuild
The script which this ebuild installs has a `/bin/sh` shebang, but uses two "bashisms" which cause problems if `/bin/sh` is dash. This can be verified either by running `dev-util/checkbashisms` on the script or by attempting to use the script with dash, where the use of `==` for comparison will cause errors and `echo -e` will not behave as expected.
An alternative fix would be to change the shebang to `/bin/bash`, but this is just the sort of simple script that doesn't need any bashisms.
Note that I only replaced `echo` with `printf` where the `-e` option was used, in order to make the changes as minimal as possible while still fixing the issue, but `printf` should generally be preferred over `echo` in shell scripts due to its greater portability.
=> app-portage/lto-rebuild: Fix bashisms in /bin/sh script

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Fails to build otherwise, `-ffat-lto-objects` doesn't work either. I didn't try every possible combination of flags but removing `-flto*` made it build without errors.
=> sys-apps/fakechroot: Disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
The `TLS relocation against invalid instruction` error as previously mentioned in #164 is still present.
=> sys-fs/btrfs-progs: disable gnu2 TLS dialect

dev-lang/python/files/python-2.7.15-PGO.patch, sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Added -fno-finite-math-only workaround for all python builds (fixes #326). Also fixed an issue in the build for python-2.7.15-r108 where failing instrumentation tests would cause the entire emerge to fail, which is not the case for the other python versions (fixes #200).
=> dev-lang/python: Fixes emerge on Ofast systems

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
dev-db/firebird fails to build with LTO, and app-office/libreoffice also fails if the firebird USE flag is enabled.
=> dev-db/firebird: Disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
`media-sound/mpc` and `sys-devel/gdb` now work fine for me after #257 got fixed in GCC 9.1.
`media-libs/libwebp` appears to be ok with `-fipa-pta` too on my machine but I left that one in since the issue still might be present under some circumstances according to #308 . I can't reproduce that though, despite building with `-Ofast` myself.
=> Remove redundant -fipa-pta workarounds

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
If `ld.gold` is used, this package fails to build with the following error:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: CMakeFiles/USBnull-0.7.0.dir/USB.cpp.o: relocation R_386_GOTOFF against preemptible symbol _USBirqHandler cannot be used when making a shared object
collect2: error: ld returned 1 exit status
```
regardless of gcc version or `CFLAGS`. If `ld.bfd` is forced, the build is successful. Note that LTO doesn't work with gcc 9.1, but does with gcc 8.3 (see https://github.com/InBetweenNames/gentooLTO/issues/339).
=> games-emulation/pcsx2: force BFD linker

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Since we already have an override of this kind for `www-client/firefox`, I believe it makes sense to do the same for all the other ebuilds that make use of `custom-cflags` and `custom-optimization` flags.
=> Set LTO_ENABLE_FLAGOMATIC=yes for ebuilds providing USE='custom-cflags custom-optimization'

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
When compiled with the flag, PHP was causing apache to segfault under certain conditions.
Also see issue #358 for more information.
=> dev-lang/php: Disable -fipa-pta

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Another `TLS relocation against invalid instruction` error.
=> sys-boot/systemd-boot: disable gnu2 TLS dialect

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
LTO disabled for sys-apps/man-db.
See #403 for more info.
=> sys-apps/man-db: Disable LTO due to runtime issues (#403)

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Added workaround for `net-libs/nodejs`. `ffinite-math-only` (implied by `-Ofast` and `-ffast-math`) causes `npm` to fail on startup.
=> net-libs/nodejs: Added `-ffinite-math-only` workaround

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Compilation fails during configure otherwise. Fixes #368 
configure:4011: checking whether the C compiler works
configure:4033: x86_64-pc-linux-gnu-gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fno-lto  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=8 -fuse-linker-plugin -pipe -falign-functions=32 conftest.c  >&5
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sys-power/nut-2.7.4-r3/temp/cccsfbwK.o: plugin needed to handle lto object …
=> sys-power/nut: Add -ffat-lto-objects

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
This works around `Floating point exception` error during the build.
=> dev-scheme/guile: disable -ffinite-math-only on -Ofast systems

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> sci-libs/tensorflow # Issue #432 tensorflow-estimator fails with missing symbol __cpu_model

sys-config/ltoize/files/patches/media-libs/dav1d/dav1d-graphite-ice-workaround.patch
disable test to workaround #442, patch courtesy of @pchome
=> media-libs/dav1d: workaround for graphite ICE, issue #442

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Versions 1.6.3-r2 and 1.6.4 do not play nice with LTO.
This is a golang application, so this is probably expected (its linker complained about the LTO flags)?
=> app-emulation/libpod: Disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
boinc_client crashes on startup due to a buffer overflow when built with -flto. Building with fat lto objects did not help on my machine. Other flags (graphite, no sem interpos, ipa, devirt) seem fine.
=> sci-misc/boinc: build without lto

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Added `-ffinite-math-only` workaround for `dev-python/numpy`, which fixes #470.
=> dev-python/numpy: Added `-ffinite-math-only` workaround

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Musescore does not compile at all. Libapparmor compiles, but causes undefined symbol errors when compiling sys-apps/apparmor
I forgot to save the build logs, I can reemerge these packages and submit them if needed
=> Changes for sys-libs/libapparmor and media-sound/musescore

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Doesn't build with '-Wl,-O1' in CFLAGS
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
=> media-video/aegisub: add workaround

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
I was attempting to build the newest available paraview (5.8.0-r2 on gentoo's default repo) and was constantly running out of memory during the build. At around 91% of the way through my RAM and swap (32 GB + 40 GB) would be maxed out (-j16). Changing to -j2 still would not fix the issue. I did not have the patience for -j1.
So after enabling all the [debugging recommendations](https://github.com/InBetweenNames/gentooLTO/wiki/Debugging#workflow-for-debugging-a-build-failure) and disabling them one-by-one, starting with `*FLAGS-=-flto*`, then `/-O3/-O2` etc., the build could finish with the graphite flags disabled. I didn't go further to remove individual `${GRAPHITE}` flags (i.e. at the time of writing was `GRAPHITE="-fgraphite-identity -floop-nest-optimize"`). If someone has any insight …
=> sci-visualization/paraview: Change CFLAGS

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Although it compiles fine without the workaround, it causes `import matplotlib.pyplot` to fail with `undefined symbol: __log_finite`.
=> dev-python/pillow: added `-fno-finite-math-only` workaround.

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> sys-fabric/libibverbs: don't build with LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
5 workarounds, included are:
media-video/mpv: disable ffast-math, a black screen was occurring when using the mitchell downscaler, or when using interpolation
sys-libs/glibc: disable ffast-math, same reason as opus (the preprocessor throws an error if ffast-math is enabled)
media-sound/mumble: disable ffast-math, same reason as opus (libopus is included as a bundled dependency)
net-libs/libtorrent-rasterbar: disable mtls-dialect=gnu2, this was causing memory corruption
www-client/torbrowser: disable mtls-dialect=gnu2, this one makes torbrowser and firefox workarounds consistent
=> Some Ofast and mtls-dialect=gnu2 workarounds

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Without the workaround, llvm would compile fine, but clang-10 would fail to emerge with error ``undefined reference to `__log10_finite'``. I wasn't able to reproduce this with the llvm/clang-9 toolchain on my machine. This seems to be a new error though, since I was previously able to emerge the llvm/clang-10 toolchain without errors. Perhaps this is due to a newer gcc/glibc?
=> sys-devel/llvm: added `-fno-finite-math-only` workaround

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
These tests were done on a x86_64 glibc system.
Note that app-emulation/libvirt failed with those changes regardless, due to sandbox issues at a later point. All others passed tests with these changes
=> Testworkarounds

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
dhclient (at least when dispatched by networkmanager) would send broken DHCPDISCOVERs , rendering it useless
=> net-misc/dhcp fix fatal runtime failure

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
See: https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/issues/1
`-flto` applied to mingw64-runtime results in errors linking errors during the compilation of `cross-{i686,x86_64}-w64-mingw32/gcc` such as:
```
libtool: link: /usr/libexec/gcc/i686-w64-mingw32/ranlib .libs/libgfortran.a
libtool: link: rm -fr .libs/libgfortran.lax .libs/libgfortran.lax
libtool: link: ( cd ".libs" && rm -f "libgfortran.la" && ln -s "../libgfortran.la" "libgfortran.la" )
make[3]: Leaving directory '/var/tmp/portage/cross-i686-w64-mingw32/gcc-9.3.0/work/build/i686-w64-mingw32/libgfortran'
make[2]: Leaving directory '/var/tmp/portage/cross-i686-w64-mingw32/gcc-9.3.0/work/build/i686-w64-mingw32/libgfortran'
make[1]: Leaving directory '/var/tmp/portage/cross-i686-w64-mingw32/gcc-9.3.0/work/build'
make: *** …
```
=> cross-{i686,x86_64}-w64-mingw32/mingw64-runtime: disable "-flto" for causing linking errors

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Gambit is a dialect of scheme that compiles scheme code to C, and calls GCC to compile it to object files or binaries. 
The error occurs at runtime. When `gsc` is built with `-flto=*` or `-ffat-lto-objects` on GCC version 9 and above, `gsc` appears to pass object files to `ld` without escaping, which causes shell expansion and build failures. E.g.
```
... compile /home/user/git/gerbil/bootstrap/lib/gerbil/core$_MOP_$_MOP_1___rt.scm
x86_64-pc-linux-gnu-gcc: error: /tmp/core/usr/bin/x86_64-pc-linux-gnu-gccMOP_/usr/bin/x86_64-pc-linux-gnu-gccMOP_1___rt.o1.xaubLa.ltrans0.o: No such file or directory
x86_64-pc-linux-gnu-gcc: warning: ‘-x lto’ after last input file has no effect
x86_64-pc-linux-gnu-gcc: fatal error: no input files
```
Where `$_` gets expanded to …
=> disable LTO on dev-scheme/gambit

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
This change fixes this error:
Failed to load /usr/lib64/xorg/modules/drivers/modesetting_drv.so: /usr/lib64/xorg/modules/drivers/modesetting_drv.so: undefined symbol: glamor_block_handler
When trying to start x11-base/xorg-server-1.20.7 with an i965 video card.
=> Fix for Undefined symbol in x11-base/xorg-server

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Build dev-libs/intel-neo with LTO caused ODR violations error
```
../compute-runtime-20.16.16582/shared/source/os_interface/linux/drm_allocation.h:14:8: error: type 'struct OsHandle' violates the C++ One Definition Rule [-Werror=odr]
14 | struct OsHandle {
|        ^
../compute-runtime-20.16.16582/opencl/source/memory_manager/os_agnostic_memory_manager.cpp:43:8: note: a different type is defined in another translation unit
43 | struct OsHandle {
|        ^
../compute-runtime-20.16.16582/shared/source/os_interface/linux/drm_allocation.h:15:19: note: the first difference of corresponding definitions is field 'bo'
15 |     BufferObject *bo = nullptr;
|                   ^
../compute-runtime-20.16.16582/opencl/source/memory_manager/os_agnostic_memory_manager.cpp:43:8: note: a type with …
```
=> dev-libs/intel-neo: disable LTO

README.md, sys-config/ltoize/files/make.conf.lto, sys-config/ltoize/files/make.conf.lto.defines
GCC 10 and higher support -flto=auto, allowing for gcc to determine
optimal number of cores to use. If -flto is set to a number, and certain
projects such as llvm are build, it will multiply this number by number
of make instances, causing too many processes to be created, ultimately
slowing down the build to a crawl on smaller devices with less ram(or
causing OOM conditions). This commit suggests using auto in configs for
ltoize and README.md.
Title: sys-config/ltoize: Suggest NTHREADS="auto" in documentation and samples
Closes #565 
Closes #527
=> Suggest NTHREADS="auto" in documentation and samples

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
```
during IPA pass: cp
lto1: internal compiler error: Segmentation fault
```
Tested flags with just `-flto`, gcc 10.2.0
=> dev-util/radare2: *FLAGS-=-flto* (ICE)

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
As per https://github.com/InBetweenNames/gentooLTO/issues/143 Mesa could now be safely compiled with LTO and that’s in fact a default for some other distros, like Arch.
=> Re-enable LTO for Mesa

sys-config/ltoize/ltoize-0.9.2.ebuild, sys-config/ltoize/ltoize-0.9.3-r1.ebuild, sys-config/ltoize/ltoize-0.9.3-r2.ebuild, sys-config/ltoize/ltoize-0.9.3.ebuild, sys-config/ltoize/ltoize-0.9.4-r1.ebuild, sys-config/ltoize/ltoize-0.9.4.ebuild, sys-config/ltoize/ltoize-0.9.6.ebuild, sys-config/ltoize/ltoize-0.9.7.ebuild
**Title:** sys-config/ltoize: Made the warn message more understandable
Community member (@uniminin) asked me for help with with this ebuild that was failing because he had version 9.3.0 installed where i believe that the current method could be confusing for some users thus reasoning for this merge request.
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>
=> sys-config/ltoize: Made the warn message more understandable

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> ltoworkarounds: remove a fdevirtualize-at-ltrans workaround

app-portage/lto-rebuild/lto-rebuild-0.9.8.ebuild
lto-rebuild works fine on arm64, so adding ~arm64 to avoid ~* and ** in
arm64 users keyword file.
Title: app-portage/lto-rebuild: add arm64 keyword
lto-rebuild works fine on arm64, so adding ~arm64 to avoid ~* and ** in
=> app-portage/lto-rebuild: add arm64 keyword

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Fixes https://github.com/InBetweenNames/gentooLTO/issues/577
=> Disable LTO for mesa on i965

sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch
Integration of Clear Linux's 'multi-thread-default.patch'
By default, zstd uses one core for compression. This patch
makes zstd use all physical cores detected for compression,
increasing performance and reducing compression time.
Below's results are from using zstd's built-in benchmark,
showing a decrease of 78.13% in compression time with -T0.
The benefit is only apparent if compression is CPU-bound
and will differ based on machine and file contents.
Default (-T1)
19#linux-5.8.tar     : 983869440 -> 121381009 (8.106),  4.05 MB/s ,1771.3 MB/s
zstd -T1 -b19 -i0 --priority=rt linux-5.8.tar  244.99s user 0.46s system 99% cpu 4:05.47 total
Patched default (-T0)
19#linux-5.8.tar     : 983869440 -> 121384544 (8.105),  19.2 MB/s ,1756.7 MB/s
zstd -T0 -b19 -i0 --priority=rt linux-5.8.tar …
=> app-arch/zstd: multithreaded compression by default

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Closes gentooLTO/issues/#592
Without it when compiling an impossible optimization breaks the process
```src/tss2-fapi/ifapi_helpers.c: In function ‘ifapi_asprintf’:
/usr/include/bits/stdio2.h:213:1: error: inlining failed in call to ‘always_inline’ ‘vasprintf.localalias’: function not inlinable
213 | __NTH (vasprintf (char **__restrict __ptr, const char *__restrict __fmt,
| ^~~~~```
=> app-crypt/tpm2-tss: Added workaround for -fno-semantic-interposition

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
just some misc LIBTOOL overrides I've found.
app-text/enchant NOCOMMON_OVERRIDE_LIBTOOL=yes
dev-util/umockdev NOCOMMON_OVERRIDE_LIBTOOL=yes (fails to build, but with unrelated error see #372 )
app-text/evince NOCOMMON_OVERRIDE_LIBTOOL=yes
=> Some misc LIBTOOL overrides

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
error: inlining failed in call to ‘always_inline’ ‘read.localalias’: function not inlinable
Compiles with workaround
=> workaround: net-libs/libiscsi fails to compile with -fno-semantic-interposition

sys-config/ltoize/files/patches/media-libs/x264/lto.patch
From #538 Thanks @Cognomines!
Title: media-libs/x264
This fixes the patch error with x264, but you have to use x264-9999 for it to work.
=> Update lto.patch for x264 (need to use x264-9999)

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
If `newlib` is compiled with LTO enabled `arm-none-eabi-gcc` will crash when compiling a project that was generated by STM32CubeMX.
`make` log: [newlib-lto-segfault.log](https://github.com/InBetweenNames/gentooLTO/files/5241255/newlib-lto-segfault.log)
I think the important bit from the log is this:
```
during IPA pass: materialize-all-clones
In function '_exit':
lto1: internal compiler error: Segmentation fault
0x7efd4bf1baaf ???
/usr/src/debug/sys-libs/glibc-2.32-r1/glibc-2.32/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7efd4bf88263 ???
../sysdeps/x86_64/multiarch/../strchr.S:32
0x7efd4bf039c9 __libc_start_main
../csu/libc-start.c:314
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See …
```
=> cross-arm-none-eabi/newlib: Disable lto

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Add libvirt in the -fipa-pta workarounds to fix a segfault when starting libvirt daemon.
Without this fix:
```
$ gdb libvirtd                                      
(gdb) run
Starting program: /usr/sbin/libvirtd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c06530 in virLogOutputListFree () from /usr/lib64/libvirt.so.0
```
With this fix: libvirtd starts normally.
=> Fix segfault when starting libvirtd

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Desactivate LTO for nextcloud-client to fix a segfault at start.
Without this fix:
```
Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
0x00007fffeec6f861 in ?? () from /usr/lib64/libQt5Core.so.5
```
With this fix: `nextcloud` starts normally.
=> net-misc/nextcloud-client: Fixes segfault by turning off LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
=> dev-python/libvirt-python Disable LTO on versions >=6.8.0 due to ICE

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
The 78.3.1 ebuild now enables LTO with the lto use flag
=> >=dev-lang/spidermonkey-78.3.1 Disable fipa-pta, segfault during build

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Building rocr-runtime with LTO causes tools like rocminfo or clinfo (and presumably many others) to segfault at runtime.
Had to disable LTO completely, building with fat objects didn't solve the issue.
=> dev-libs/rocr-runtime: Build without LTO

dev-lang/python/python-3.10.0_alpha1-r1.ebuild, dev-lang/python/python-3.7.9-r1.ebuild, dev-lang/python/python-3.8.6-r1.ebuild, dev-lang/python/python-3.9.0-r1.ebuild
Closes #552 
I haven't actually tested them all but the diffs are the same
=> dev-python=>3.7.9: use --pgo-extended

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Disable lto entirely, otherwise it segfaults on start since Qt 5.15.1
Fixes issue:
https://github.com/InBetweenNames/gentooLTO/issues/622
=> app-admin/keepassxc: disable lto, otherwise segfaults on start

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Similar to other rust programs, `sccache` needs `-ffat-lto-objects` to build.
=> dev-util/sccache: Fails to link without -ffat-lto-objects

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Title: app-text/yodl:  Disable LTO
yodl doesn't build with LTO, this PR disables LTO so yodl can be compiled.
=> Disable LTO for app-text/yodl

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Title: net-news/newsboat: disable LTO
Disable LTO for net-news/newsboat, package fails to build with LTO.
=> Disable LTO for net-news/newsboat

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
When compiled with lto, gjs produces general protection faults when gdm starts up.
```
Nov 11 13:21:47 terra kernel: traps: gnome-shell[2631] general protection fault ip:7ff8ee6c03b0 sp:7ffc03d827d0 error:0 in libgjs.so.0.0.0[7ff8ee68d000+82000]                                                     
Nov 11 13:21:47 terra systemd[1]: Started Process Core Dump (PID 2681/UID 0).                                                                                                                                      
Nov 11 13:21:47 terra systemd-coredump[2682]: [🡕] Process 2631 (gnome-shell) of user 997 dumped core.                                                                                                              
Nov 11 13:21:47 terra systemd[1]: systemd-coredump@4-2681-0.service: …
```
=> dev-libs/gjs: Disabled LTO because of runtime errors

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Fixes buffer overflow error when running an autosetup script, which `mail-client/neomutt` uses in it's configure script.
This is the error message when attempting to merge `mail-client/neomutt` with SEMINTERPOS enabled in `dev-lang/jimtcl`.
```
>>> Configuring source in /var/tmp/portage/mail-client/neomutt-20201127-r1/work/neomutt-20201127 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 CCACHE=none --disable-doc --enable-nls --enable-notmuch --enable-gpgme --disable-pgp --disable-smime --disable-bdb --enable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --disable-idn --disable-gss --enable-lmdb …
```
=> dev-lang/jimtcl: disable SEMINTERPOS

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Package sys-libs/efivar-37 fails with the following error:
```
Error: invalid attempt to declare external version name as default in symbol `efi_set_variable@@LIBEFIVAR_0.24'
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
```
Adding "-flto-partition=none" to CFLAGS fixes the issue.
Upstream bug report: https://github.com/rhboot/efivar/issues/156
=> sys-libs/efivar-37: Added -flto-partition=none

app-portage/lto-rebuild/lto-rebuild-0.9.8-r1.ebuild
Default Source Directory Setting
In EAPI versions before 5, the variable `S` would default to `${WORKDIR}/${P}`. But if `${P}` did not exist, the ebuild would silently fall back to the work directory (`${WORKDIR}`). For some ebuilds, this wasn't a problem because they only installed files out of `${FILESDIR}` or `${SYSROOT}`. 
Starting with EAPI 5, the PM no longer does this automatic fallback to `${WORKDIR}`. If you get errors like "`The source directory '...' doesn't exist`", then you're hitting this problem (i.e. relying on the older silent fallback behavior).
The easy answer is usually to set `S` to `${WORKDIR}`.This might not be the right answer (maybe your source lives somewhere else), but frequently this is OK. So after the `DEPEND/RDEPEND` variables and before any of the src_* or …
=> lto-rebuild: set source directory to ${WORKDIR}

sys-config/ltoize/files/patches/app-arch/zstd-1.4.7/zstd-1.4.7-multi-thread-default.patch
This applies to app-arch/zstd-1.4.7, enabling the multiprocessor as default option
It's the continuation of #664 and #663
=> Enable multiprocessor for zstd by default

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Closes #581 
If the building tools (`gnustep-base/gnustep-base`) is built with LTO,
when the base program is compiled the error in #581 appears, since the
building tools doesn't play well with LTO
=> Fix for issue #581

sys-config/ltoize/files/patches/dev-libs/gmp/arm64-lto.patch
This fixes gmp-6.2.1 on arm64 - without, it breaks with lto, resulting in e.g. gfortran being stuck in an infinite loop
Patch is submitted upstream aswell - I'll submit to ::gentoo once upstream explains what's going on and wether this is the right approach
=> fix broken gcc due to gmp on arm64

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
GZDoom doesn't build otherwise, unfortuanetly. According to [this issue](https://github.com/InBetweenNames/gentooLTO/issues/524), it also doesn't work with ninja. Although I didn't test this for myself, I disabled it too just in case.
=> games-fps/gzdoom: Disabled LTO + Force Emake

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
`flac -d` works fine without it on my system with gcc 10.2.0
It also breaks configure with clang, as clang doesn't support the flag.
=> ltoworkarounds: remove media-libs/flac -fno-ipa-cp-clone

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Similar to GZDoom, Zandronum doesn't start when LTO is enabled. Though, interestingly, it will run, but it can't properly read Doom .wad files. Both GZDoom and Zandronum are based off of ZDoom, so that could be it.
=> games-fps/zandronum: Disabled LTO

README.md, sys-config/ltoize/files/bashrc.d/44-lto-clang-full.sh, sys-config/ltoize/files/package.cflags/clang.conf, sys-config/ltoize/ltoize-0.9.9.ebuild, sys-config/ltoize/metadata.xml
```
--- sys-config/ltoize/ltoize-0.9.8.ebuild       2021-01-25 22:34:28.457112681 +1300
+++ sys-config/ltoize/ltoize-0.9.9.ebuild       2021-01-25 22:34:14.813000000 +1300
@@ -5,7 +5,7 @@
inherit toolchain-funcs
-DESCRIPTION="A configuration for portage to make building with LTO easy."
+DESCRIPTION="A configuration for portage to make building with LTO easy"
HOMEPAGE="https://github.com/InBetweenNames/gentooLTO"
#Note: there's nothing preventing this from working on stable, but the dependencies of ltoize aren't keyworded for
@@ -16,20 +16,17 @@
LICENSE="GPL-2+"
SLOT="0"
-IUSE="override-flagomatic keep-nocommon"
+IUSE="clang keep-nocommon override-flagomatic"
#portage-bashrc-mv can be obtained from mv overlay
DEPEND="
-       >=sys-devel/binutils-2.32:*
-       >=sys-devel/gcc-config-1.9.1 …
```
=> introduce clang.conf

sys-config/ltoize/files/package.cflags/lto.conf
*FLAGS=-flto* forcefully enables lto, and breaks all other *FLAGS. 
Fixed before, it seems
=> dev-db/firebird: package.cflags typo

sys-config/ltoize/files/package.cflags/clang.conf
fixed in dev-libs/libgcrypt-1.9.1
https://dev.gnupg.org/T5255
=> clang.conf: remove dev-libs/libgcrypt workaround

README.md, sys-config/ltoize/files/make.conf.lto
This PR will allow for package and use flag managers to work with gentooLTO, referenced here: #320 and here: #660. In my opinion, this is the way to resolve both cleanly, although I understand any adversity towards absolute over relative paths. Seeing as portage configuration should be stored in `/etc/portage/` however, absolute paths shouldn't matter and I think this is the way to go about fixing those issues.
=> change relative paths to absolute

sys-config/ltoize/files/package.cflags/portage-bashrc-mv.conf, sys-config/ltoize/ltoize-0.9.10.ebuild
Fixes #690
If you're having a dependency issue while attempting to rebuild it, first try downgrading colm and then updating ragel (pulls in newer colm).
=> dev-util/colm: disable remove-la from portage-bashrc-mv

sys-config/ltoize/files/package.cflags/no-semantic-interposition.conf
```/var/tmp/portage/dev-util/umockdev-0.12.1/work/umockdev-0.12.1/src/libumockdev-preload.c: In function 'get_rdev':
/usr/include/bits/unistd.h:145:1: error: inlining failed in call to 'always_inline' 'readlink.localalias': function not inlinable
145 | __NTH (readlink (const char *__restrict __path, char *__restrict __buf,
| ^
/var/tmp/portage/dev-util/umockdev-0.12.1/work/umockdev-0.12.1/src/libumockdev-preload.c:189:9: note: called from here
189 |     if (readlink(buf, link, sizeof(link)) < 0) {
|         ^```
=> dev-util/umockdev: Disable -fno-semantic-interposition

sys-config/ltoize/files/package.cflags/lto.conf
Compiles without errors, but breaks applications, such as gnome-maps
See [https://gitlab.gnome.org/GNOME/folks/-/issues/123](https://gitlab.gnome.org/GNOME/folks/-/issues/123)
This lets gnome-maps and gnome-contacts launch.
There are still things crashing and journal spam when the program launches, but it seems functional.
unrelated note, media-video/totem still won't launch
=> dev-libs/folks: Disable LTO

sys-config/ltoize/files/package.cflags/optimizations.conf
Most forms of scrolling in okular have been broken for a while (mouse wheel over the document, arrow keys, page up/down, clicking on links in the document or in the thumbnails/outline). I recently found that it was caused by building qtcore with `-ffinite-math-only`.
=> dev-qt/qtcore: Added Ofast workaround to fix scrolling in kde-apps/okular

sys-config/ltoize/files/package.cflags/ipa-pta.conf
RADV (AMDGPU) and Intel GPUs crash with Vulkan and IPAPTA enabled.
Vulkan was not working since mesa 21.1 on my AMD 6800xt when I used RADV (segfault). I found this post advising to remove IPAPTA, which indeed fixed the issue for me: https://forums.gentoo.org/viewtopic-t-1134963-highlight-mesa.html
=> media-libs/mesa: disable IPAPTA to fix segfault

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Fails during linking with GCC 11.1.0
=> media-libs/dav1d: Disable LTO

sys-config/ltoize/files/package.cflags/ltoworkarounds.conf
Build failures starting with 24.0 . Not entirely surprising, as this release came with significant VM changes to support JIT.
=> dev-lang/erlang: Disable LTO

sys-config/ltoize/files/package.cflags/clang.conf
=> app-office/libreoffice: build with clang and/or custom-cflags

sys-config/ltoize/files/package.cflags/optimizations.conf
with -O3 it compiles fine but homectl starts acting up.
homed logins and new user creations via `homectl create` fail with protocol error.
=> sys-apps/systemd: set optimizations to O2

sys-config/ltoize/files/package.cflags/lto.conf
log: https://pastebin.com/UNN2sX4U
The log doesn't seem to show any noticeable building error, but disabling LTO does make the package built successfully. I'm sorry for the lack of explanation!
=> dev-util/github-cli: disable LTO

sys-config/ltoize/files/package.cflags/ipa-pta.conf
XWayland applications querying for GLX information (glxinfo,
spotify, lutris, anything GPU accelerated) crash the X server
when XWayland is compiled with -fipa-pta.
Fixes #766
=> x11-base/xwayland: disable -fipa-pta to fix crash on GLX query

sys-config/ltoize/files/package.cflags/lto.conf, sys-config/ltoize/files/package.cflags/optimizations.conf
net-libs/nodejs: There's `lto` USE flag that should be used to inject `-flto` instead, also LTO currently does not work with GCC 11 (you'll be asked to disable the USE flag when you try to emerge it).
app-editors/emacs: You'll be explicitly asked to disable `-ffinite-math-only` during emerge.
gui-apps/gammastep: Fork of `x11-misc/redshift`, `-ffinite-math-only` breaks it in the exactly same way.
=> net-libs/nodejs: filter out -flto from *FLAGS; -Ofast workarounds

sys-config/ltoize/files/package.cflags/lto.conf
Fixes #772 and #746 
If it's bad to include 2 fixes in one PR, let me know, this is my first submission to this repo
=> net-analyzer/wireshark and dev-lang/lua: disable LTO 

sys-config/ltoize/files/package.cflags/ipa-pta.conf
Added a workaround for GCC 11.2.0 bug that causes git to be miscompiled with `-flto -fipa-pta`.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101949
https://bugs.gentoo.org/809419
=> dev-vcs/git: disable -fipa-pta

sys-config/ltoize/files/package.cflags/ipa-pta.conf
=> dev-lang/duktape: disable IPAPTA

sys-config/ltoize/files/package.cflags/optimizations.conf
kde-apps/cantor will fail build with -O3 but works perfectly fine with -O2, graphite, and other optimizations enabled by ltoize.
=> kde-apps/cantor: will not build with -O3

sys-config/ltoize/files/package.cflags/lto.conf
app-misc/openrgb will complete build successfully however will generate a core dump due to a segmentation fault, on launch.
=> app-misc/openrgb: segmentation fault will occur on launch with LTO enabled

sys-config/ltoize/ltoize-0.9.11.ebuild
Fixes #473. 
dosym seems to silently adds $EPREFIX to some parts of its arguments, see https://bugs.gentoo.org/615594. This is a hackish way of having Prefix install the symlinks at the expected location.
I updated the documentation to reflect that Prefix cannot use the make.conf.lto symlink, at it sources an absolute path that is not present in Prefix.
I'd appreciate testing on real Gentoo, as I only have access to Prefix right now.
=> sys-config/ltoize: install symlinks at proper location in Prefix
